Controllers/CinemaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.WebSockets;

namespace Midterm_Project.Controllers
{
    public class CinemaController : Controller
    {
        private readonly DataContext _context;
        public CinemaController(DataContext context)
        {
            _context = context;
        }
        // GET: CinemaController
        public ActionResult ShowAll()
        {
            var listCinema = _context.Cinemas.Select(c=>c);
            return View(listCinema);
        }

        // GET: CinemaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CinemaController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: CinemaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([BindAttribute("Name", "AmountDefault")] Cinema cinema)
        {
            try
            {
                _context.Cinemas.Add(cinema);
                _context.SaveChanges();
                return RedirectToAction(nameof(ShowAll));
            }
            catch
            {
                return View();
            }
        }

        // GET: CinemaController/Edit/5
        public ActionResult Edit(int id)
        {
            var existCinema = _context.Cinemas.FirstOrDefault(c => c.ID == id);
            if (existCinema != null)
            {
                return View(existCinema);
            } else
            {
                return NotFound();
            }
            
        }

        // POST: CinemaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [BindAttribute("Name", "AmountDefault")] Cinema cinema)
        {
            try
            {
                var existCinema = _context.Cinemas.FirstOrDefault(c => c.ID == id);
                if (existCinema != null)
                {
                    existCinema.Name = cinema.Name;
                    existCinema.AmountDefault = cinema.AmountDefault;
                    _context.SaveChanges();
                }

                return RedirectToAction(nameof(ShowAll));
            }
            catch
            {
                return View();
            }
        }

        // GET: CinemaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CinemaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/FilmController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Midterm_Project.Controllers
{
    public class FilmController : Controller
    {
        private readonly DataContext _context;
        public FilmController(DataContext context)
        {
            _context = context;
        }
        // GET: FilmController
        public ActionResult ShowAll()
        {
            var listFilm = _context.Films.Select(f => f);
            return View(listFilm);
        }

        // GET: FilmController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FilmController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FilmController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Name", "Time")] Film film)
        {
            try
            {
                _context.Films.Add(film);
                _context.SaveChanges();
                return RedirectToAction(nameof(ShowAll));
            }
            catch
            {
                return View();
            }
        }

        // GET: FilmController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FilmController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FilmController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FilmController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Midterm_Project.Controllers
{
    public class OrderController : Controller
    {
        private readonly DataContext _context;
        public OrderController(DataContext context)
        {
            _context = context;
        }
        // GET: HomeController1
        // GET: OrderController
        public IActionResult GetAllOrder(int? scheduleId)
        {
            IEnumerable<Order> list = null;
            if (scheduleId == null || scheduleId == 0)
            {
                list = _context.Orders.Select(o => o).Include("FilmSchedule").Include("FilmSchedule.Film").Include("FilmSchedule.Cinema");
            }
            else
            {
                list = _context.Orders.Where(o => o.FilmScheduleID == scheduleId).Include("FilmSchedule").Include("FilmSchedule.Film").Include("FilmSchedule.Cinema");
            }

            return Json(list);
        }
        public ActionResult ShowAll(int? scheduleId)
        {
            IEnumerable<Order> list;

            if (scheduleId == null || scheduleId == 0)
            {
                list = _context.Orders.Select(o => o).Include("FilmSchedule").Include("FilmSchedule.Film").Include("FilmSchedule.Cinema");
            } else
            {
                list = _context.Orders.Where(o => o.FilmScheduleID == scheduleId).Include("FilmSchedule").Include("FilmSchedule.Film").Include("FilmSchedule.Cinema");
            }
            ViewBag.OrderList = list;
            
            ViewBag.FilmScheduleID = new[] { new SelectListItem { Text = "Vui lòng chọn lịch chiếu", Value = "-1" }, new SelectListItem { Text = "Tất cả", Value = "0" } }.Concat(
                    _context.FilmSchedules.Select(f => new SelectListItem { Text = f.Film.Name + "-" + f.Cinema.Name + "-" + f.PremiereTime.ToString(), Value = f.ID.ToString() })
                );
            
            return View(list);
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            ViewBag.FilmScheduleID = new[] { new SelectListItem { Text = "Vui lòng chọn lịch chiếu", Value = "-1" } }.Concat(
                    _context.FilmSchedules.Select(f => new SelectListItem { Text = f.Film.Name + "-" + f.Cinema.Name + "-" + f.PremiereTime.ToString(), Value = f.ID.ToString() }));

            return View();
        }

        public int CountTicketRemain(int scheduleId)
        {
            var amount = _context.FilmSchedules.FirstOrDefault(f => f.ID == scheduleId).AmountEmpty;
            return amount;
        }
        public bool CheckCorrectAmount(int ticketRemain, int amountTicket)
        {
            return amountTicket <= ticketRemain;
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("PhoneNumber, FilmScheduleID, AmountTicket")] Order order)
        {
            try
            {
                //ViewBag.MaxTicket = _context.FilmSchedules.FirstOrDefault(f => f.ID == order.FilmScheduleID).AmountEmpty;
                var filmScheduleTicketRemain = _context.FilmSchedules.FirstOrDefault(f => f.ID == order.FilmScheduleID).AmountEmpty;
                var existFilmSchedule = _context.FilmSchedules.FirstOrDefault(f => f.ID == order.FilmScheduleID);
                if (order.AmountTicket <= filmScheduleTicketRemain)
                {
                    existFilmSchedule.AmountEmpty -= order.AmountTicket;
                    _context.Orders.Add(order);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(ShowAll));
                } else
                {
                    ViewBag.FilmScheduleID = new[] { new SelectListItem { Text = "Vui lòng chọn lịch chiếu", Value = "-1" } }.Concat(
                    _context.FilmSchedules.Select(f => new SelectListItem { Text = f.Film.Name + "-" + f.Cinema.Name + "-" + f.PremiereTime.ToString(), Value = f.ID.ToString() }));
                    return View();
                } 

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Midterm_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Midterm_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Midterm_Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="ShowAll">Cinema</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="ShowAll">Film</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FilmSchedule" asp-action="ShowAll">Film Schedule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ShowAll">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Midterm_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>